---
- name: install tomcat server
  hosts: tomcatvm
  

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless

  - name: download tomcat server packages
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-10/v10.0.18/bin/apache-tomcat-10.0.18.tar.gz
      dest: /root/tomcat/

  - name: extract tomcat packages
    unarchive:
      src: /root/ansibleplaybookcap/apache-tomcat-9.0.44.tar.gz
      dest: /root/tomcat/
      remote_src: yes

  - name: start tomcat services
    shell: nohup /root/tomcat/apache-tomcat-9.0.44/bin/startu
